### PR TITLE
Memory increase & fix in file-based auth conn

### PR DESCRIPTION
**Pull request by irentu**

### CODE REVIEW

**Comment by Mercynary** [comment]
Seems some dependency version is missing. Can you rebase your branch.

**Comment by irentu** [comment]
Rebased.

**Comment by stfnsche** [comment]
oesb still fails to build. see travis log.

**Comment by irentu** [comment]
The problem had nothing to do with the changes introduced by this PR. Indeed I let the travis build once more. The problem is gone. Probably was a temporary one. However, now the tests do not succeed to finish in 50 min, which again has nothing to do with this PR.

**Pull request merged**
